name: consultar_clima
description: 'Consult weather now'
publish_to: 'none'
version: 0.0.1
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  http: ^1.1.0
dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  mocktail: ^1.0.1

flutter:

  uses-material-design: true
